### ISSUE TITLE
Questions about some details.

### ISSUE THREAD

**Issue by chenerg** [KelianB/SPARK#3]
In Figure 2, it is observed that the neutral template is optimized during training. In your paper, it is also stated as follows:

>  D is initialized in a separate supervised pre-training stage that minimizes the squared norm ||D(𝛾(𝑥)) − E||2 at the positions of the canonical FLAME vertices, such that the network initially mimics the FLAME expression basis E.

 Therefore, are the blendshapes for the current identity also optimized? Is this statement true?

**Comment by KelianB** [comment]
Hi,
The citation only refers to the expression blendshapes. For the identity blendshapes, we use the mean prediction from the initial pre-processing of the sequences (during which we also get our pose and expression coefficients for each frame). We then optimize vertex offsets on top of the neutral FLAME template with identity shapes.

**Comment by chenerg** [comment]
That's clear, thanks!
