### ISSUE TITLE
Editing example on project page

### ISSUE THREAD

**Issue by NikoBele1** [KelianB/SPARK#9]
How was the editing example of obama with a beard done? Do you imported a tracked scene into a 3d modelling software and edit the tracked 3d model manually?

And in addition, is there a way to drive one reconstruction with a second of a different person, to perform reenactment?

**Comment by NikoBele1** [comment]
Thanks a lot for the thorough response, i'll take a look!

**Comment by IamMohitM** [comment]
Is there a template texture image provided/available for the overlay video?

**Comment by KelianB** [comment]
The one I used is the mean texture computed using this repo: https://github.com/TimoBolkart/BFM_to_FLAME
For licensing reasons I think you have to do that yourself, but let me know if I can help.

**Comment by IamMohitM** [comment]
@KelianB Maybe noob question, are you referring to the `FLAME_albedo_from_BFM.npz` file as the texture image?

**Comment by KelianB** [comment]
You should be able to get the texture image from that file, something like this:
```python
import numpy as np
from PIL import Image
tex = np.load("./FLAME_albedo_from_BFM.npz")
tex = tex["MU"].float().reshape(512, 512, 3)[..., (2,1,0)]
tex = np.rint(tex * 255).astype(np.uint8)
im = Image.fromarray(tex)
im.save("tex_mean.png")  
```

**Comment by FernandoConti** [comment]
Dear Mr. Baert,

Incredible work!

I had a question, would it be easy for you to show how to export the deformed heads frame by frame for the reenactment, like morph targets as it were? Or does that need a lot of scripting?

Thanks!

**Comment by KelianB** [comment]
Hi, I just made a basic example in this PR: #15
Feel free to add whatever you need. Please comment on that PR for further questions; I will now close this issue.
